steps:
  # Build the container image
  - name: 'gcr.io/cloud-builders/docker'
  args:
    [
      'build',
      '-t',
      'us-central1-docker.pkg.dev/wally-registry-403720/cloud-run-source-deploy:$COMMIT_SHA',
      '-f',
      'wally-registry-backend/Dockerfile',
      '.',
    ]

  # Push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/wally-registry-403720/cloud-run-source-deploy:$COMMIT_SHA']

   # Deploy container image to Cloud Run
  - name: "gcr.io/cloud-builders/gcloud"
    args:
      [
        "run",
        "deploy",
        "wally-registry-backend",
        "--image",
        "gcr.io/wally-registry/cloud-run-source-deploy:$COMMIT_SHA",
        "--region",
        "us-central1",
        "--platform",
        "managed",
        "--command",
        "./launch",
        "--allow-unauthenticated",
      ]

timeout: 900s
options:
 logging: CLOUD_LOGGING_ONLY
 machineType: 'E2_HIGHCPU_8'